---
title: "Read and plot GLODAPv2 data"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(stats)
```

```{r read_mask_files, include = FALSE}

landmask <-  read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "land_mask_WOA18.csv"
  )
)

```

```{r ggplot_theme, include = FALSE}
# ggplot theme for all plots
theme_set(theme_bw())
```

# Read csv files

```{r read_files}

# read variable forcing model regrid data in August
variable_data_tibble <- read_csv(
  here::here(
    "data",
    "variable_DIC_2007.csv"
  )
)

# read GLODAPv2 depth regrided data
GLODAP <- read_csv(
  here::here(
    "data",
    "GLODAP_regrid_depth.csv"
  )
)

```

# Modify data

```{r modify_data, include = FALSE}

# calculate annual average and filter surface DIC in 2007
variable_data_tibble_annual_average_surface <- variable_data_tibble %>%
  group_by(lat, lon, depth, basin_AIP) %>%
  summarise(DIC_variable = mean(DIC_variable)) %>%
  rename(DIC = DIC_variable) %>%
  filter(depth == 5)

```

```{r subset_model_data}

# convert varibale DIC time to month
variable_data_tibble_month <- variable_data_tibble %>%
  mutate(time = month(time)) %>%
  rename(month = time, DIC = DIC_variable)

# convert GLODAP time to month
GLODAP_month <- GLODAP %>%
  mutate(date = month(date)) %>%
  rename(month = date)

# select model data where there is a corresponding observational data
joint_obs_model <- left_join(GLODAP_month, variable_data_tibble_month) %>%
  select(lon, lat, month, depth, tco2, DIC)

# interpolate model-obs subset
#joint_obs_model <- joint_obs_model %>%
#  group_by(lon, lat, month) %>%
#  ifelse(sum(is.na(DIC)) > 1, mutate(DIC = approxfun(depth, DIC, method = "linear")(depth), NA)) %>%
#  ungroup()

```

# Plot joint obs vs model

```{r plot_joint_obs_model_DIC}

# plot GLODAP observation and model data
ggplot() + 
  geom_raster(data = variable_data_tibble_annual_average_surface,
             aes(lon, lat, fill = DIC)) +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0) +
  geom_point(data = GLODAP_month,
             aes(lon, lat)) +
  geom_raster(data = landmask,
              aes(lon, lat), fill = "grey80") +
  labs(title = "Observation and Model DIC Distribution", subtitle = "Model DIC Depth: 5m | Annual Average", x = "Longitude", y = "Latitude", fill = "DIC [mmol/m3]") 

rm(GLODAP, GLODAP_month, joint_obs_model, variable_data_tibble, variable_data_tibble_annual_average_surface, variable_data_tibble_month)

```
