---
title: "Read and plot GLODAPv2 data"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

```{r read_mask_files, include = FALSE}

landmask <-  read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "land_mask_WOA18.csv"
  )
)

```

```{r ggplot_theme, include = FALSE}
# ggplot theme for all plots
theme_set(theme_bw())
```

# Read csv files

```{r read_files}

# read variable forcing model regrid data in August
variable_regrided_Aug <- read_csv(
  here::here(
    "data",
    "variable_regrided_Aug.csv"
  )
)

# read GLODAPv2 depth regrided data
GLODAP <- read_csv(
  here::here(
    "data",
    "GLODAP_regrid_depth.csv"
  )
)

```

# Modify data

```{r modify_data}

# convert GLODAP time to month
GLODAP <- GLODAP %>%
  mutate(date = month(date)) %>%
  rename(month = date)

# select GLODAP August data
GLODAP_Aug <- GLODAP %>%
  filter(month == 8)

# select model data where there is a corresponding observational data
joint_obs_model <- left_join(GLODAP_Aug, variable_regrided_Aug) %>%
  arrange(lon, lat, month, depth) %>%
  select(lon, lat, month, depth, tem, TEMP, sal, SALT, tco2, DIC, talk, ALK, nitrate, NO3, phosphate, PO4, silicate, SiO3, oxygen, O2, aou, AOU)

```

# Plot joint obs vs model
```{r plot_joint_obs_model}

# plot GLODAP observation and model data
variable_regrided_Aug_surface <- variable_regrided_Aug %>%
  filter(depth == 5)

ggplot() + 
  geom_raster(data = variable_regrided_Aug_surface,
             aes(lon, lat, fill = DIC)) +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0) +
  geom_point(data = GLODAP_Aug,
             aes(lon, lat)) +
  geom_raster(data = landmask,
              aes(lon, lat), fill = "grey80") +
  labs(title = "Observation and Model Data Distribution", subtitle = "Model DIC Depth: 5m | Month: August", x = "Longitude", y = "Latitude", fill = "DIC [mmol/m3]") 

```
