---
title: "Read model data"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library, message = FALSE, warning = FALSE}
library(tidyverse)
library(stars)
library(collapse)
library(lubridate)
```

```{r read_mask_files, include = FALSE}

basinmask <- read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "basin_mask_WOA18_AIP.csv"
  )
)
basinmask <- basinmask %>%
  select(-basin)

landmask <-  read_csv(
  here::here(
    "data/World_Ocean_Atlas_2018/_summarized_files",
    "land_mask_WOA18.csv"
  )
)

```

```{r ggplot_theme, include = FALSE}
# ggplot theme for all plots
theme_set(theme_bw())
```

# Read regridded variable forcing DIC in 2007

```{r read_regridded_variable_DIC}

# set path to model output files
path_model_regridded <- "/net/kryo/work/loher/CESM_output/RECCAP2/regridded/"

# read list of all files
file_list <- list.files(path = path_model_regridded, pattern = "*2020_DIC_2007.nc")
print(file_list)

# select item out of file_list
file <- file_list[1]

# read in data
variable_data <-
  read_ncdf(paste(
    path_model_regridded,
    file,
    sep = ""
  ),
  var = "DIC")
  
# convert to tibble
variable_data_tibble <- variable_data %>%
  as_tibble()
  
# convert longitudes
variable_data_tibble <- variable_data_tibble %>%
  mutate(lon = if_else(lon < 20, lon + 360, lon))
  
# mutate variables and filter NaN value
variable_data_tibble <- variable_data_tibble %>%
  rename(depth = z_t, DIC_variable = DIC) %>%
  mutate(depth = depth / 100) %>%
  filter(!is.na(DIC_variable)) %>%
  mutate(DIC_variable = as.numeric(DIC_variable))

# select data included in basinmask
variable_data_tibble <- inner_join(variable_data_tibble, basinmask) 

# calculate annual average DIC in 2007
variable_data_tibble_annual_average <- variable_data_tibble %>%
  group_by(lat, lon, depth, basin_AIP) %>%
  summarise(DIC_variable = mean(DIC_variable))

# write file
variable_data_tibble_annual_average %>%
  write_csv(here::here("data",
                       "variable_DIC_AA_2007.csv"))

rm(variable_data)

```

# Read regridded normal forcing DIC in 2007

```{r read_regridded_normal_DIC}

# set path to model output files
path_model_regridded <- "/net/kryo/work/loher/CESM_output/RECCAP2/regridded/"

# read list of all files
file_list <- list.files(path = path_model_regridded, pattern = "*cstCO2_DIC_2007.nc")
print(file_list)

# select item out of file_list
file <- file_list[1]

# read in data
normal_data <-
  read_ncdf(paste(
    path_model_regridded,
    file,
    sep = ""
  ),
  var = "DIC")
  
# convert to tibble
normal_data_tibble <- normal_data %>%
  as_tibble()
  
# convert longitudes
normal_data_tibble <- normal_data_tibble %>%
  mutate(lon = if_else(lon < 20, lon + 360, lon))
  
# mutate variables and filter NaN value
normal_data_tibble <- normal_data_tibble %>%
  rename(depth = z_t, DIC_normal = DIC) %>%
  mutate(depth = depth / 100) %>%
  filter(!is.na(DIC_normal)) %>%
  mutate(DIC_normal = as.numeric(DIC_normal))

# select data included in basinmask
normal_data_tibble <- inner_join(normal_data_tibble, basinmask) 

# calculate annual average DIC in 2007
normal_data_tibble_annual_average <- normal_data_tibble %>%
  group_by(lat, lon, depth, basin_AIP) %>%
  summarise(DIC_normal = mean(DIC_normal))

# write file
normal_data_tibble_annual_average %>%
  write_csv(here::here("data",
                       "normal_DIC_AA_2007.csv"))

rm(normal_data, normal_data_tibble, normal_data_tibble_annual_average)

```


# Select model subset based on observations in 2007


## Read csv files

```{r read_csv_files}

# read GLODAPv2 depth regridded data
GLODAP <- read_csv(
  here::here(
    "data",
    "GLODAP_regrid_depth.csv"
  )
)

```

## Modify data

```{r subset_model_data}

# calculate annual average and filter surface DIC in 2007 for plotting
variable_data_tibble_annual_average_surface <- variable_data_tibble_annual_average %>%
  filter(depth == 5) %>%
  rename(DIC = DIC_variable)

# convert variable DIC time to month
variable_data_tibble_month <- variable_data_tibble %>%
  mutate(time = month(time)) %>%
  rename(month = time, DIC = DIC_variable)

# convert GLODAP time to month
GLODAP_month <- GLODAP %>%
  mutate(date = month(date)) %>%
  rename(month = date) %>%
  select(month, lon, lat, depth, tco2) %>%
  unique()

# subset model data at the observation sites
model_subset <- left_join(GLODAP_month, variable_data_tibble_month) %>%
  select(lon, lat, month, depth, DIC) %>%
  unique()

# interpolate model subset
model_subset <- model_subset %>%
  group_by(lon, lat, month) %>% 
  mutate(n = sum(!is.na(DIC))) %>% 
  ungroup()

model_subset_interpo <- model_subset %>%
  filter(n > 1) %>%
  group_by(lon, lat, month) %>%
  arrange(depth) %>%
  mutate(DIC = approxfun(depth, DIC, rule = 2)(depth)) %>%
  ungroup()

model_subset <- model_subset %>%
  filter(n == 1) %>%
  filter(!is.na(DIC))

model_subset_interpo <- full_join(model_subset_interpo, model_subset)
  
# combine model data with corresponding observational data
joint_obs_model <- left_join(model_subset_interpo, GLODAP_month) %>%
  select(lon, lat, month, depth, tco2, DIC)

```

# Plot joint obs vs model

```{r plot_joint_obs_model_DIC}

# plot GLODAP observation and model data
ggplot() + 
  geom_raster(data = variable_data_tibble_annual_average_surface,
             aes(lon, lat, fill = DIC)) +
  scale_fill_viridis_c() +
  coord_quickmap(expand = 0) +
  geom_point(data = GLODAP_month,
             aes(lon, lat)) +
  geom_raster(data = landmask,
              aes(lon, lat), fill = "grey80") +
  labs(title = "Observation and Model DIC Distribution", subtitle = "Model DIC Depth: 5m | Annual Average", x = "Longitude", y = "Latitude", fill = "DIC [mmol/m3]") 

rm(GLODAP, GLODAP_month, joint_obs_model,  variable_data_tibble,variable_data_tibble_annual_average,  variable_data_tibble_annual_average_surface, variable_data_tibble_month, model_subset, model_subset_interpo)

```
