---
title: "Read and plot GLODAPv2 data"
author: "Donghe Zhu and Dr Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Required Packages
```{r Load_package}
library(tidyverse)
library(lubridate)
```

```{r read_model_dile, include = FALSE}

variable_data_tibble_annual_average <-  read_csv(
  here::here(
    "data",
    "variable_DIC_AA_2007.csv"
  )
)

```

```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```

# Read GLODAPv2 data

```{r read_obs_and_regrid_depth}

# set path to GLODAP files
path_GLODAP <- "/net/kryo/work/updata/glodapv2_2020/"

# read list of all files
file_list <- list.files(path = path_GLODAP, pattern = "*_File.csv")
print(file_list)

# select item out of file_list
file <- file_list[1]

# read in GLODAP data
GLODAP <-
  read_csv(paste(
    path_GLODAP,
    file,
    sep = ""
    ),
    na = "-9999",
    col_types = cols(.default = col_double())
  )

# select relevant columns
GLODAP <- GLODAP %>%
  select(cruise:talkqc)

# create date column
GLODAP <- GLODAP %>%
  mutate(date = ymd(paste(year, month, day))) %>%
  relocate(date)

# harmonize column names
GLODAP <- GLODAP  %>%
  rename(sal = salinity,
         tem = temperature)

# harmonize coordinates
GLODAP <- GLODAP  %>%
  rename(lon = longitude,
         lat = latitude) %>%
  mutate(lon = if_else(lon < 20, lon + 360, lon))

# remove irrelevant columns
GLODAP <- GLODAP %>%
  select(-c(day:minute,
            maxsampdepth, bottle, sigma0:sigma4,
            nitrite:nitritef))

# filter GLODAP in year 2007 and select tCO2
GLODAP <- GLODAP %>%
  filter(year == 2007) %>%
  filter(!is.na(tco2)) %>%
  select(lon, lat, month, depth, tco2)

# group into 1*1 intervals
GLODAP <- GLODAP %>% 
  mutate(lat = cut(lat, seq(-90, 90, 1), seq(-89.5, 89.5, 1)),
         lat = as.numeric(as.character(lat)),
         lon = cut(lon, seq(20, 380, 1), seq(20.5, 379.5, 1)),
         lon = as.numeric(as.character(lon)))

# set depth range
depth_model <- unique(variable_data_tibble_annual_average$depth)
range_temp <- 1:(length(depth_model) - 1)
for (i in 1:(length(depth_model) - 1))  {
  range_temp[i] <- (depth_model[i] + depth_model[i + 1]) / 2
}
  range <- c(0)
  range <- append(range, range_temp) 
  range <- append(range, Inf)
  print(range)

# convert observational depth to 60 model depth
GLODAP <- GLODAP %>%
  mutate(depth = cut(depth, range, depth_model), depth = as.numeric(as.character(depth)))

# write file
GLODAP %>%
  write_csv(here::here("data",
                       "GLODAP_regrid_2007.csv"))

rm(GLODAP, variable_data_tibble_annual_average, depth_model, range, range_temp, i)

```
