---
title: "read_model_data"
author: "Donghe Zhu"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

##

```{r,Load package}
library(ncdf4)
library(ggplot2)
library(dplyr)
library(stars)
library(tidync)
library(tidyselect)
```

Read in file and extract variable DIC
```{r Read in file and extract variable DIC, eval=FALSE}
# read in file
nc_data <- tidync(here::here("data",
                      "GIAF_JRA.pop.h.0354.nc"))

# extract variable DIC
DIC <- nc_data %>%
  hyper_tibble(select_var = "DIC")

# rename DIC label
DIC <- DIC %>%
  rename(lon = Var1,
         lat = Var2,
         depth = Var3,
         month = Var4) %>%
  filter(depth == 1 & month == 8)
print(DIC)
```

Map of surface DIC value 
```{r, eval=FALSE}
ggplot() +
  geom_raster(data=var,aes(x = lon, y = lat, fill = value)) +
  scale_fill_distiller(palette = 'Spectral', direction = 1) +
  scale_y_continuous(breaks=c(1,95,190,285,384),labels=c("-80","-40","0","40","80")) +
  scale_x_continuous(breaks=c(1,80,160,240,320),labels=c("320","50","140","230","320"))

```

section_global_coordinates
```{r, eval=FALSE}
library(readr)
library(geosphere)
library(tidyr)

parameters <- data.frame(
  lon_Atl_section = 335.5,
  lat_section_N = 60.5,
  lat_section_S = -60.5,
  lon_Pac_section = 190.5,
  lat_max = 65
)

landsea_01 <- read_csv(here::here("data",
                                  "landsea_01.msk"),
                         skip = 1,
                         col_types = list(.default = "d"))

basinmask_01 <- read_csv(here::here("data",
                                    "basinmask_01.msk"),
                         skip = 1,
                         col_types = list(.default = "d"))

# diff
basinmask_01 <- basinmask_01 %>% 
  select(Latitude: Longitude) %>%
  rename(lat = Latitude, lon = Longitude)

section <- basinmask_01 %>%
  select(lon, lat)

Atl_NS <- section %>%
  filter(
    lon == parameters$lon_Atl_section,
    lat <= parameters$lat_section_N,
    lat >= parameters$lat_section_S
  ) %>%
  arrange(-lat)

Atl_SO <- section %>%
  filter(lon > parameters$lon_Atl_section,
         lat == parameters$lat_section_S) %>%
  arrange(lon)

Pac_SO <- section %>%
  filter(lon < parameters$lon_Pac_section,
         lat == parameters$lat_section_S) %>%
  arrange(lon)

Pac_SN <- section %>%
  filter(
    lon == parameters$lon_Pac_section,
    lat <= parameters$lat_section_N,
    lat >= parameters$lat_section_S
  ) %>%
  arrange(lat)

section_global_coordinates <- bind_rows(Atl_NS,
                     Atl_SO,
                     Pac_SO,
                     Pac_SN)

#section_global_coordinates <- section_global_coordinates %>%
#  mutate(lon_180 = if_else(lon > 180, lon - 360, lon))

section_global_coordinates <- section_global_coordinates %>%
  mutate(dist_int = distGeo(cbind(lon, lat)) / 1e6) %>%   # diff
  mutate(dist = cumsum(dist_int))

section_global_coordinates <- section_global_coordinates %>%
  select(lon, lat, dist) %>% 
  drop_na()


rm(Atl_NS, Atl_SO, Pac_SN, Pac_SO, section)

var <- melt(ncvar_get(nc_data, "DIC"))
var <- var %>%
  rename(lon = Var1,
         lat = Var2,
         depth = Var3,
         month = Var4)
```

```{r, eval=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
# seperate Pacific, Atlantic, Indian Oceans
basinmask_01 <- read_csv(here::here("data",
                                    "basinmask_01.msk"),
                         skip = 1,
                         col_types = list(.default = "d"))

basinmask_01 <- basinmask_01 %>% 
  select(Latitude:Basin_0m) %>% 
  mutate(Basin_0m = as.factor(Basin_0m)) %>% 
  rename(lat = Latitude, lon = Longitude)

landsea_01 <- read_csv(here::here("data",
                                    "landsea_01.msk"),
                         skip = 1,
                         col_types = list(.default = "d"))

landsea_01 <- landsea_01 %>% 
  rename(lat = Latitude, lon = Longitude)

basinmask_01 <- basinmask_01 %>% 
  filter(Basin_0m %in% c("1", "2", "3", "10", "11", "12", "56"),
         lat <= parameters$lat_max) %>% 
  mutate(basin_AIP = "none",
         basin_AIP = case_when(
           Basin_0m == "1" ~ "Atlantic",
           Basin_0m == "10" & lon >= -63 & lon < 20 ~ "Atlantic",
           Basin_0m == "11" ~ "Atlantic",
           Basin_0m == "3" ~ "Indian",
           Basin_0m == "10" & lon >= 20 & lon < 147 ~ "Indian",
           Basin_0m == "2" ~ "Pacific",
           Basin_0m == "12" ~ "Pacific",
           Basin_0m == "56" ~ "Pacific",
           Basin_0m == "10" & lon >= 147 | lon < -63 ~ "Pacific")) %>% 
  select(-Basin_0m) 
#  mutate(lon = if_else(lon < 20, lon + 360, lon))

ggplot() +
  geom_raster(data = landsea_01,
              aes(lon, lat), fill = "grey80") +
  geom_raster(data = basinmask_01,
              aes(lon, lat, fill = basin_AIP)) +
  scale_fill_brewer(palette = "Dark2") +
  coord_quickmap(expand = 0) +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank())

basin_Pacific <- basinmask_01 %>%
  filter(basin_AIP=="Pacific") 
basin_Indian<-basinmask_01 %>%
  filter(basin_AIP=="Indian") 
basin_Atlantic<-basinmask_01 %>%
  filter(basin_AIP=="Atlantic")

nc_data <- tidync(here::here("data",
                      "GIAF_JRA.pop.h.0354.nc"))
DIC <- nc_data %>%
  hyper_tibble(select_var = "DIC") %>%
  hyper_filter(depth = 500, month = 8)

DIC_Pacific <- left_join(basin_Pacific, DIC) %>%
  group_by(lat) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  ggplot(aes(lat, value)) +
  labs(title = "Zone Mean DIC", subtitle = "Subsection: Pacific Ocean", x = "Latitude", y = expression(paste("DIC (gC m"^-2, "s"^-1, ")")))

DIC_Indian <- left_join(basin_Indian, DIC) %>%
  group_by(lat) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  ggplot(aes(lat, value)) +
  labs(title = "Zone Mean DIC", subtitle = "Subsection: Indian Ocean", x = "Latitude", y = expression(paste("DIC (gC m"^-2, "s"^-1, ")")))

DIC_Atlantic <- left_join(basin_Atlantic, DIC) %>%
  group_by(lat) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>%
  ggplot(aes(lat, value)) +
  labs(title = "Zone Mean DIC", subtitle = "Subsection: Atlantic Ocean", x = "Latitude", y = expression(paste("DIC (gC m"^-2, "s"^-1, ")")))
```

